### ISSUE TITLE
1.15.2 config not working.

### ISSUE THREAD

**Issue by ArMoReDfUrY** [stfwi/engineers-tools#10]
forge 31.1.77
engineerstools-1.15.2-1.0.8-b1

disabling the sleeping bag has no affect.
also setting durability for the Redia tool.

**Comment by stfwi** [comment]
Hi, thanks for the hint. For whatever reason the settings are at the defaults in the config loaded event, but later in the reload event they are set. I'll take occasion to check if some other improvements can be done in this matter. Fixed will be in the next beta.

**Comment by stfwi** [comment]
Fix is implemented, schedule depending on when I can make tests this or next weekend.

**Comment by ArMoReDfUrY** [comment]
no worries. :)

**Comment by stfwi** [comment]
Alright, the dist jar is on Curse, could you take a look if the issue is resolved on your machine and close the issue if so?
 I had - after some research - decided to make the config server side only, as the "common" config is not synchronized to the clients (by Forge design). So to prevent ambiguous sided config its now in the "serverconfig" directory of the played world.

**Comment by ArMoReDfUrY** [comment]
it's good. thanks for the fix.
