### ISSUE TITLE
Client crash when crafting small fluid collection funnel

### ISSUE THREAD

**Issue by InflamedSebi** [stfwi/engineers-tools#14]
Crashlog:
https://pastebin.com/556m1ax6

Happended in a non vanilla crafting station, but retried in vanilla one with same error.

**Comment by stfwi** [comment]
Hi, ok, gotch, it's the Fluid Barrel in the Decor mod. I forgot a `EMPTY` constant check there, it's fixed for the next version. Cheers, and ty for the report details!

**Comment by stfwi** [comment]
Hi ho, can you do me a favour, I cannot reproduce the bug on my server/client, but I am very sure I know what it is. Could you double check this pre-release-build and gimme feedback if the problem is gone? (I signed the jar etc, if ok this will be the release pushed to curse).
[2020-11-14-dist-ed-1.16.3-1.1.4-test.zip](https://github.com/stfwi/engineers-tools/files/5540489/2020-11-14-dist-ed-1.16.3-1.1.4-test.zip)

**Comment by stfwi** [comment]
Hi, we had already a verification of the fix from the thread here https://github.com/stfwi/engineers-decor/issues/136, I'll close this issue, too, then. The fix version is up on Curse. Cheers,-

**Comment by InflamedSebi** [comment]
Ups sry, wasn't very active lately. Glad you still could get it to work.
Ty :)
