### ISSUE TITLE
Potential Missing crusher related Compats. Request for them to possibly get added?

### ISSUE THREAD

**Issue by Darkmega18** [stfwi/engineers-tools#18]
I'm playing in 1.16.5 currently and I'm noticing that I cannot crush tin with the hammer to get my double tin ores for thermal foundation and other mods that utilize it.

Perhaps crushing for dilithium and rutile from advanced rocketry in their own equivalents for crushing if advanced rocketry exists?

Another I think could be worth looking into as far as mod compats could be vinteum from mana and artifice? Since as far as I can tell, none of the mods I have like IE, Thermal or advanced rocketry seem to have it as potential doubleable.

On the topic of compatibility does the muslee press take oredicted seeds from like pams, thermal, crockpot etc etc? If it doesn't, might be a potential venture for compatibility in that direction also, perhaps?

**Comment by stfwi** [comment]
Hi, tin declared with forge tags should do, it's in the recipe file here: https://github.com/stfwi/engineers-tools/blob/1.16/src/main/resources/data/engineerstools/recipes/crushing/tin_grit_crushing_recipe.json.
For specific material crushing you can add own recipes in a data pack, the linked file is a good template for that.

Seeds are by default vanilla because far not every seeds of other mods are edible. Adding seeds is therefore also possible with the data pack, checkout the base tag file here: https://github.com/stfwi/engineers-tools/blob/1.16/src/main/resources/data/engineerstools/tags/items/musli_bar_seeds.json.

Let me know if you run into trouble or it keeps not working, we'll get there ;) Cheers man!

**Comment by Darkmega18** [comment]
ah geez. here we go with people referring me to datapacks again. T_T

**Comment by stfwi** [comment]
Aye, config and such has changed quite a bit with the newer MC versions. All in all, once adapted it's a quite good and unified way, like the new Forge config.
If you did not have any contact with that stuff, my recommendation would take a look at the official Minecraft wiki and install Visual Studio Code as editor. Latter helps with syntax highlighting and showing errors in JSON files. Cheers,-

**Comment by Darkmega18** [comment]
yep. I managed it eventually. I had been tired that night to try new stuff, but screwed around with it and managed to get all tins working properly into thermal tin dust and rutiles and titaniums into advanced rocketry titaniums and vinteum done. And further took apart thermal and put them into pulverizers and smelting where needed.

**Comment by stfwi** [comment]
oky I'll close this one then. Cheers,-
