### ISSUE TITLE
[Enhancement] [1.12] Steel Hoe

### ISSUE THREAD

**Issue by Federsavo** [stfwi/engineers-tools#9]
Immersive add every steel item except hoe and since they aren't updating 1.12 anymore you could add it (if you want I have the texture available).

P.s. I am the same guy from Engineer's decor :)

**Comment by stfwi** [comment]
Hi, uhm, I have to think about this, currently I do not have a "set" where all tools are included, a single hoe item might look strange in this context. 
The REDIA tool has already hoeing function, although I have to admit it's not primarily made for hoeing purposes - more intended to be a tool that you always have at hand e.g. for repairing a farmland block rather than tilling a whole field.

Is your idea more about completing the IE set or more having something for efficient hoeing?

**Comment by Federsavo** [comment]
Yeah, I undersatnd it's a strange feature but it's more about completing the set of IE steel tools than efficient hoeing. 
You can do it if you have some time to waste but it's not a priority for sure.

**Comment by stfwi** [comment]
We should also double check with Blu, because the basic steel tool set is in the IE core.
If I now think more about it - this mod is also required to work standalone ... we would have a steel hoe without other steel tools ... lets sleep a few days over that and check with BluSunrize.

**Comment by stfwi** [comment]
Ok, quickly synced with Blu, can you open the feature request in the IE repository?
(https://github.com/BluSunrize/ImmersiveEngineering/issues). 
I'll close with a "redirect" then ;-)
